name = "roim-picx"
compatibility_date = "2026-04-21"
pages_build_output_dir = "dist"

[vars]
BASE_URL = "http://image.bitzhong.cc"
PICX_AUTH_TOKEN = "ylwtsmtjfyhdcmgscwhssybzsdkc"
ALLOW_TOKEN_LOGIN = "true"

# 你的 KV 绑定
[[kv_namespaces]]
binding = "XK"
id = "2bd268d322c74ea39fb7789b57e48cc6"

# 你的 R2 绑定
[[r2_buckets]]
binding = "PICX"
bucket_name = "roim-imgs"

# 你的 D1 绑定
[[d1_databases]]
binding = "DB"
database_name = "roim-d1"
database_id = "92f79cb8-45fd-4df8-b2e6-90e0a3efb582"
